# Generated by Django 3.2 on 2022-12-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(null=True),
        ),
    ]
