# Generated by Django 3.2 on 2022-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20221214_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
