# Generated by Django 3.2 on 2022-12-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_comentario_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='slug',
        ),
    ]
